### ISSUE TITLE
ICFG crashes!

### ISSUE THREAD

**Issue by ghaffarian** [ghaffarian/progex#1]
ICFG crashes with a `NullPointerException` given the following test case:
[Test3.txt](https://github.com/ghaffarian/progex/files/1347020/Test3.txt)

Note that other analyses (such as CFG and PDG) run successfully on the same test case.

Here is the stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at progex.java.JavaICFGBuilder$ICFGVisitor.findMethodbyName(JavaICFGBuilder.java:858)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprPrimary(JavaICFGBuilder.java:587)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprPrimary(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$ExprPrimaryContext.accept(JavaParser.java:7443)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprDotID(JavaICFGBuilder.java:600)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprDotID(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$ExprDotIDContext.accept(JavaParser.java:7617)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprMethodInvocation(JavaICFGBuilder.java:693)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprMethodInvocation(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$ExprMethodInvocationContext.accept(JavaParser.java:7257)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitVariableInitializer(JavaBaseVisitor.java:265)
	at progex.java.parser.JavaParser$VariableInitializerContext.accept(JavaParser.java:2948)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitVariableDeclarator(JavaBaseVisitor.java:251)
	at progex.java.parser.JavaParser$VariableDeclaratorContext.accept(JavaParser.java:2829)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitVariableDeclarators(JavaBaseVisitor.java:244)
	at progex.java.parser.JavaParser$VariableDeclaratorsContext.accept(JavaParser.java:2765)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitLocalVariableDeclaration(JavaICFGBuilder.java:468)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitLocalVariableDeclaration(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$LocalVariableDeclarationContext.accept(JavaParser.java:5322)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitLocalVariableDeclarationStatement(JavaBaseVisitor.java:496)
	at progex.java.parser.JavaParser$LocalVariableDeclarationStatementContext.accept(JavaParser.java:5267)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitBlockStatement(JavaBaseVisitor.java:489)
	at progex.java.parser.JavaParser$BlockStatementContext.accept(JavaParser.java:5203)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitBlock(JavaICFGBuilder.java:251)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitBlock(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$BlockContext.accept(JavaParser.java:5136)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitTryStatement(JavaICFGBuilder.java:413)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitTryStatement(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$TryStatementContext.accept(JavaParser.java:5438)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitBlockStatement(JavaBaseVisitor.java:489)
	at progex.java.parser.JavaParser$BlockStatementContext.accept(JavaParser.java:5203)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitBlock(JavaICFGBuilder.java:251)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitBlock(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$BlockContext.accept(JavaParser.java:5136)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitMethodBody(JavaBaseVisitor.java:356)
	at progex.java.parser.JavaParser$MethodBodyContext.accept(JavaParser.java:3924)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitMethodDeclaration(JavaICFGBuilder.java:505)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitMethodDeclaration(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$MethodDeclarationContext.accept(JavaParser.java:1913)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitMemberDeclaration(JavaBaseVisitor.java:160)
	at progex.java.parser.JavaParser$MemberDeclarationContext.accept(JavaParser.java:1797)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitClassBodyDeclaration(JavaBaseVisitor.java:153)
	at progex.java.parser.JavaParser$ClassBodyDeclarationContext.accept(JavaParser.java:1681)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitClassBody(JavaBaseVisitor.java:139)
	at progex.java.parser.JavaParser$ClassBodyContext.accept(JavaParser.java:1547)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitClassDeclaration(JavaICFGBuilder.java:231)
	at progex.java.JavaICFGBuilder$ICFGVisitor.visitClassDeclaration(JavaICFGBuilder.java:144)
	at progex.java.parser.JavaParser$ClassDeclarationContext.accept(JavaParser.java:811)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitTypeDeclaration(JavaBaseVisitor.java:41)
	at progex.java.parser.JavaParser$TypeDeclarationContext.accept(JavaParser.java:452)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at progex.java.parser.JavaBaseVisitor.visitCompilationUnit(JavaBaseVisitor.java:20)
	at progex.java.parser.JavaParser$CompilationUnitContext.accept(JavaParser.java:214)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:82)
	at progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:46)
	at progex.graphs.cfg.ICFGBuilder.buildForAll(ICFGBuilder.java:24)
	at progex.Execution.execute(Execution.java:211)
	at progex.Main.main(Main.java:32)
```

**Comment by ghaffarian** [comment]
This issue is now fixed with the latest commit.
