### ISSUE TITLE
Error while creating ICFG

### ISSUE THREAD

**Issue by Samarjeet93** [ghaffarian/progex#14]
The code in the file JavaClassExtractor looks for path "\lib\src.zip" which is not available.

Interprocedural Control-Flow Analysis
=====================================
java.nio.file.NoSuchFileException: lib\src.zip
java.nio.file.NoSuchFileException: lib\src.zip
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1842)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1160)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:140)
	at ghaffarian.progex.java.JavaClassExtractor.extractJavaLangInfo(JavaClassExtractor.java:52)
	at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:72)
	at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:46)
	at ghaffarian.progex.graphs.cfg.ICFGBuilder.buildForAll(ICFGBuilder.java:24)
	at ghaffarian.progex.Execution.execute(Execution.java:219)
	at ghaffarian.progex.Main.main(Main.java:36)

Process finished with exit code 0

**Comment by Samarjeet93** [comment]
Help needed!!!

**Comment by Samarjeet93** [comment]
@ghaffarian

**Comment by ghaffarian** [comment]
Sorry for the late reply!

Did you check previous closed issues similar to yours?

For example checkout these:
- [FileNotFoundException: lib/src.zip](https://github.com/ghaffarian/progex/issues/7)
- [FileNotFoundException lib\src.zip](https://github.com/ghaffarian/progex/issues/12)

Reply back if you still have issues with this.
