### ISSUE TITLE
Error when generating  ICFG

### ISSUE THREAD

**Issue by YinHuiLin** [ghaffarian/progex#15]
Before all, thank you for your excellent work ,it is very helpful for me.
But when I use command line for generating ICFG, some errors was reported as below:
````
java.io.FileNotFoundException: lib\src.zip 
java.io.FileNotFoundException: lib\src.zip 
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at ghaffarian.progex.java.JavaClassExtractor.extractJavaLangInfo(JavaClassExtractor.java:52)
        at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:72)
        at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:46)
        at ghaffarian.progex.graphs.cfg.ICFGBuilder.buildForAll(ICFGBuilder.java:24)
        at ghaffarian.progex.Execution.execute(Execution.java:219)
        at ghaffarian.progex.Main.main(Main.java:36)
````
So how to deal with it?
Thank you in advance for your help.
Lin

**Comment by ghaffarian** [comment]
Hi Lin;

Thanks for  your kind words.

This issue is previously reported by other users as well.

Unfortunately I currently don't have enough time to fix this issue very soon, but I may be able to work on this in the next month or so.

I think you can find a work around easily. Just check out the previous issues.

Let me know if I can provide any help on this.

Cheers

**Comment by copernico** [comment]
https://github.com/ghaffarian/progex/issues?q=is%3Aissue+++lib%5Csrc.zip

**Comment by copernico** [comment]
> But when I use command line for generating ICFG, some errors was reported as below:
>.....
> So how to deal with it?

https://github.com/ghaffarian/progex/issues?q=is%3Aissue+++lib%5Csrc.zip
