### ISSUE TITLE
IllegalArgumentException: no such vertex in graph: 0: ELSE

### ISSUE THREAD

**Issue by ghaffarian** [ghaffarian/progex#2]
While processing `progex.java.JavaDDGBuilder.java` from PROGEX's own source code, the following exception is thrown during control-dependency analysis (`JavaCDGBuilder`), after processing line `620: debug("METHOD DEF INFO NOT FOUND!");` of the `JavaDDGBuilder.java` file:
```
Exception in thread "main" java.lang.IllegalArgumentException: no such vertex in graph: 0: ELSE
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:132)
	at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:178)
	at progex.java.JavaCDGBuilder$ControlDependencyVisitor.checkBuildFollowRegion(JavaCDGBuilder.java:670)
	at progex.java.JavaCDGBuilder$ControlDependencyVisitor.addNodeEdge(JavaCDGBuilder.java:642)
	at progex.java.JavaCDGBuilder$ControlDependencyVisitor.visitStatementExpression(JavaCDGBuilder.java:175)
	at progex.java.JavaCDGBuilder$ControlDependencyVisitor.visitStatementExpression(JavaCDGBuilder.java:51)
...
```
The issue is most likely related to the `else if (...)` statement at line 585; which may not be processed correctly by `JavaCDGBuilder`.

The input Java file is attached below:
[JavaDDGBuilder.java.txt](https://github.com/ghaffarian/progex/files/1404898/JavaDDGBuilder.java.txt)

**Comment by ghaffarian** [comment]
I was able to narrow down the input test program to the following small Java program:
[TestX.java.txt](https://github.com/ghaffarian/progex/files/1410846/TestX.java.txt)

The above small program replicates the issue just like the original large input program.

This will help more in tracing and understanding the source of the issue.

**Comment by ghaffarian** [comment]
The issue is now fixed with the latest commit.
