### ISSUE TITLE
NullPointerException @ JavaICFGBuilder.java:1079

### ISSUE THREAD

**Issue by ghaffarian** [ghaffarian/progex#3]
When running PROGEX's ICFG analysis on its own source code, the following exception is thrown:
```
Exception in thread "main" java.lang.NullPointerException                                                                                                                                                         
        at progex.java.JavaICFGBuilder$ICFGVisitor.classInstantiate(JavaICFGBuilder.java:1079)                                                                                                                    
        at progex.java.JavaICFGBuilder$ICFGVisitor.findClassbyName(JavaICFGBuilder.java:993)                                                                                                                      
        at progex.java.JavaICFGBuilder$ICFGVisitor.findVariableType(JavaICFGBuilder.java:969)                                                                                                                     
        at progex.java.JavaICFGBuilder$ICFGVisitor.visitExprPrimary(JavaICFGBuilder.java:627) 
...
```

More precisely, the exception is raised while analysing line 32 of `progex.java.JavaClass.java`, which is:
```
    fields = new ArrayList<>();
```

The source of the issue is at line 1079 of `JavaICFGGuilder.java` inside the `classInstantiate(...)` method declaration, which is:
```
    String[] genericParam = params.split(",");
```
At this point a `NullPointerException` is raised, because `params` is `null`. This is most probably due to not handling the case where the generic type parameter is empty (e.g. `new ArrayList<>();`).

**Comment by ghaffarian** [comment]
This issue is now fixed with latest commits by @h-homaei.
