### ISSUE TITLE
FileNotFoundException: lib/src.zip

### ISSUE THREAD

**Issue by omah69** [ghaffarian/progex#7]
Hello,

When I try to execute ICFG I have this problem:

java.io.FileNotFoundException: lib/src.zip (Aucun fichier ou dossier de ce type)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:126)
        at ghaffarian.progex.java.JavaClassExtractor.extractJavaLangInfo(JavaClassExtractor.java:52)
        at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:72)
        at ghaffarian.progex.java.JavaICFGBuilder.buildForAll(JavaICFGBuilder.java:46)
        at ghaffarian.progex.graphs.cfg.ICFGBuilder.buildForAll(ICFGBuilder.java:24)
        at ghaffarian.progex.Execution.execute(Execution.java:226)
        at ghaffarian.progex.Main.main(Main.java:36)

What does that mean ? 

I use this command line: 
java -jar "/home/progex-3.2.0/progex.jar" -outdir /home/progex-3.2.0/output/synapse_1.0 -icfg -lang java -format dot /home/progex-3.2.0/projets_source/synapse_1.0

**Comment by ghaffarian** [comment]
As the exception message says, it can't find the required file `src.zip` in the `lib` directory. You are probably trying to run this after cloning the repo and building from source. Note that for several reasons the `src.zip` file (which is the source-code for the JDK standard libraries) is not included in the source-code repository, but is available in the release distributions.

Go to the [releases page](https://github.com/ghaffarian/progex/releases) and download the latest stable release (currently `v3.2.0`) and after extracting, you can find the `lib` directory which contains the `src.zip` file. You need to put this `lib` directory alongside the executable JAR file of PROGEX.

**Comment by ghaffarian** [comment]
It's worth noting that even after fixing this, you still might encounter some issues with the ICFG analysis. The ICFG analysis has some known issues, but it was developed by a friend of mine which currently doesn't have time to work on it (I really doubt he would ever get to fix this!).

The ICFG analysis is not a priority for myself either, so I won't be working on this either.

**Comment by ghaffarian** [comment]
I double checked this, and we have some changes in the latest release of **PROGEX**:
- the `src.zip` has been renamed to `jdk7-src.zip`
- the file is no more in the `lib` directory, but in the `res` directory.

If the ICFG analysis requires the `lib/src.zip` file, you can copy and rename the file as required.
This should most probably fix your problem.
